stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.8.1-jdk-11
  script:
    - mvn clean install

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y openssh-client
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -i /root/.ssh/id_rsa ec2-user@$EC2_INSTANCE_IP "mkdir -p /home/ec2-user/myapp"
    - scp -i /root/.ssh/id_rsa $CI_PROJECT_DIR/target/myapp.jar ec2-user@$EC2_INSTANCE_IP:/home/ec2-user/myapp/
    - ssh -i /root/.ssh/id_rsa ec2-user@$EC2_INSTANCE_IP "nohup java -jar /home/ec2-user/myapp/myapp.jar > /dev/null 2>&1 &"
